# HU S3 Project

###
# group: auth
# @name Register
POST localhost:8080/api/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "firstName": "Ad",
  "lastName": "Min"
}

###
# group: auth
# @name Login
POST localhost:8080/api/login
#Accept: application/hal+json
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

> {%
if (response.status === 200) {
    client.global.set("authToken", response.body.token);
}

%}

###
# @name Get Current Login
GET localhost:8080/api/login
Authorization: Bearer {{authToken}}

###
# @name Get All Users
GET localhost:8080/api/users
Authorization: Bearer {{authToken}}

###
# @name Get Single User
GET localhost:8080/api/users/admin
Authorization: Bearer {{authToken}}