# HU S3 Project

###
# group: auth
# @name Register
POST localhost:8080/api/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "firstName": "Ad",
  "lastName": "Min"
}

###
# group: auth
# @name Login
POST localhost:8080/api/login
#Accept: application/hal+json
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

> {%
if (response.status === 200) {
    const authHeader = response.headers.valueOf("Authorization");
    const token = authHeader.substring(7);
    client.global.set("authToken", token);
}

%}
