# Todos

GET localhost:8080/api/todos
Authorization: Bearer {{authToken}}
###

POST localhost:8080/api/todos
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "title": "Test Todo"
}

###

GET localhost:8080/api/todos/1
Authorization: Bearer {{authToken}}
###

PUT localhost:8080/api/todos/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "title": "Test Todo edited",
  "completed": true
}

###

DELETE localhost:8080/api/todos/1
Authorization: Bearer {{authToken}}
###